import Head from "next/head";
import React, { useState, useRef, useEffect } from "react";
import Heading from "./Components/Heading";
import Projects from "./Components/Projects";
import SubHeading from "./Components/SubHeading";
function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={`px-10 md:px-20 lg:px-40 ${
          darkMode ? "bg-gray-900 dark:text-white" : "bg-D3D3D3"
        }`}
      >
        <Heading darkMode={darkMode} setDarkMode={setDarkMode} />
        <section className="py-10">
          <SubHeading />
          <Projects darkMode={darkMode} />
        </section>
      </main>
    </div>
  );
}
export default Home;
